Update website
QuantEcon/website pull request #113
Opened 2023-08-01 02:51 UTC by HengchengZhang

2023-08-07 05:07 UTC, mmcky commented
@HengchengZhang can you please update the top level comment box with a short list of things that have changed. Then I will review and take a look.

2023-08-07 05:07 UTC, mmcky commented
- [ ] fix merge conflict

2023-08-08 00:57 UTC, HengchengZhang commented
Thanks @mmcky, this PR is still subject to changes and I will ping you once its ready.

2023-08-12 11:14 UTC, Smit-create commented on _posts/2023-07-31-jax.md
> +
Should this file be renamed to remove `jax` suffix and add `africa-workshop`?

2023-09-18 04:26 UTC, mmcky commented
@HengchengZhang can you please update this to fix the merge conflict and bring it up to date so I can review. Thanks.

2023-09-18 04:27 UTC, mmcky commented on _posts/2023-07-31-jax.md
> +
@HengchengZhang can you take care of this comment

2023-09-18 05:32 UTC, mmcky commented
@HengchengZhang is it possible to have this ready for review tomorrow?

2023-09-19 06:08 UTC, mmcky commented
@HumphreyYang -- once @HengchengZhang fixes this merge conflict. It would be great if you could take a look across this PR as well. I will also review -- we just want to get this migration right. Any comments are welcome.

2023-09-24 12:11 UTC, HengchengZhang commented
Sorry for my late reply and such a big PR, please have a look at the commits @mmcky and @HumphreyYang and please ping me for more changes/details.

2023-09-24 23:44 UTC, HumphreyYang commented
Many thanks @HengchengZhang, I will go through this and then pass it on to @mmcky.

Hi @mmcky, could you please grant me access to this repo? Many thanks in advance.

2023-09-24 23:50 UTC, mmcky commented
thanks @HengchengZhang for the the updates. 

@HumphreyYang I added write access for you last week so you should be good to go. 👍

2023-09-26 05:59 UTC, HumphreyYang requested changes
Many thanks @HengchengZhang. This looks great to me. Please kindly see my comments above.

2023-09-26 05:59 UTC, HumphreyYang commented on _layouts/home.html
> +    <div class="container">
We have two containers: one for the first row (lectures and code libraries) and one for the second row (Dynamic Programming and Economic Networks), which takes a while to appear when we scroll down the page with the fade-in animation.

Should we put them under one container?

2023-09-26 05:59 UTC, HumphreyYang commented on _layouts/home.html
>                <p><a href="/projects/#filter=lecture" class="btn-learn-more">Browse lectures</a></p>
The `filter=lecture` does not work anymore, given we changed the layout of the projects page.

The link takes us to the "other projects" page:
https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app/projects#filter=lecture 

(Same as filter=code)

The link should be

```
/lectures/
```

2023-09-26 05:59 UTC, HumphreyYang commented on _layouts/home.html
>                <p><a href="/projects/#filter=code" class="btn-learn-more">View libraries</a></p>
The same issue as `filter=lecture`

2023-09-26 05:59 UTC, HumphreyYang commented on _layouts/home.html
> +              <p><img src="/assets/img/dp-image.png" class="img-thumbnail" alt="Screenshot showing a lecture page"></p>
Is this `alt` accurate?

```suggestion
              <p><img src="/assets/img/dp-image.png" class="img-thumbnail" alt="Icon of Dynamic Programming book"></p>
```

2023-09-26 05:59 UTC, HumphreyYang commented on _layouts/home.html
> +              <p><img src="/assets/img/networks-image.png" class="img-thumbnail" alt="Screenshot showing python code">
Same as above. This `alt` should be changed to something like

```suggestion
              <p><img src="/assets/img/networks-image.png" class="img-thumbnail" alt="Icon of Economic Networks book">
```

2023-09-26 05:59 UTC, HumphreyYang commented on pages/code.md
> +</div>
This shows projects rather than the code page as intended:

https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app/packages/

(Original: https://quantecon.org/projects/#filter=code)

2023-09-26 05:59 UTC, HumphreyYang commented on pages/projects.md
> +permalink: projects
Should we call it `other_projects` for debugging purposes? 

Original links to projects are directed to other projects now.

2023-09-26 05:59 UTC, HumphreyYang commented on _posts/2023-07-31-africa-workshop.md
> +![](/assets/img/africa-workshop.jpeg)
Should we delete this, as it is already on our published page now? It is now showing this post twice : )

2023-10-25 02:43 UTC, mmcky commented
@HengchengZhang are you able to review and incorporate @HumphreyYang feedback and then ping me for a final review. 

We need to resolve this PR as soon as possible.

2023-10-25 03:45 UTC, mmcky commented
Thanks @HengchengZhang 

I know there is a drive to simplify these pages -- but I think this page would look better with the card style objects (as we had on the more complex filtered page). So perhaps we can try static pages (with the card style objects) 

<img width="1332" alt="Screenshot 2023-10-25 at 2 42 27 pm" src="https://github.com/QuantEcon/website/assets/8263752/e2246538-c929-4d63-b186-129cf425209a">


the card style is

<img width="1332" alt="Screenshot 2023-10-25 at 2 44 11 pm" src="https://github.com/QuantEcon/website/assets/8263752/73131858-dd2b-4606-9f47-5b46e0ca944d">

then we can make use of the filters on the `lectures` page to filter for `language` such as `julia` and `python`

2023-10-25 04:11 UTC, mmcky commented on _layouts/home.html
> +    <div class="container">
@HumphreyYang I am in favour of a single container. I think that matches the behaviour of the other blocks as well.

2023-10-25 04:11 UTC, mmcky commented on _layouts/home.html
>                <p><a href="/projects/#filter=lecture" class="btn-learn-more">Browse lectures</a></p>
@HengchengZhang please do a grep and fix all instances to the correct page

2023-10-25 04:12 UTC, mmcky commented on _posts/2023-07-31-africa-workshop.md
> +![](/assets/img/africa-workshop.jpeg)
@HumphreyYang if this is showing twice it should be deleted.

2023-10-25 04:13 UTC, mmcky commented
@HengchengZhang the left is this branch while the right is the live site

Do you know why this icon is a bird and not the compact QE?

<img width="773" alt="Screenshot 2023-10-25 at 3 12 45 pm" src="https://github.com/QuantEcon/website/assets/8263752/d55f4dee-bb33-4134-b06c-852088fcf23c">

2023-10-25 04:14 UTC, mmcky commented
@HengchengZhang can you please let me know if you have time to fix these items this week?

2023-10-25 04:14 UTC, HengchengZhang commented
> Thanks @HengchengZhang
> 
> I know there is a drive to simplify these pages -- but I think this page would look better with the card style objects (as we had on the more complex filtered page). So perhaps we can try static pages (with the card style objects)
> 
> <img alt="Screenshot 2023-10-25 at 2 42 27 pm" width="1332" src="https://user-images.githubusercontent.com/8263752/277866566-e2246538-c929-4d63-b186-129cf425209a.png">
> the card style is
> 
> <img alt="Screenshot 2023-10-25 at 2 44 11 pm" width="1332" src="https://user-images.githubusercontent.com/8263752/277866850-73131858-dd2b-4606-9f47-5b46e0ca944d.png">
> then we can make use of the filters on the `lectures` page to filter for `language` such as `julia` and `python`

Thanks @mmcky and main reason I'm making it simpler is that John thought that it's not very nice if we don't have 3's multiplier's number of cards. Cause currently if we go to the lectures filter there will be one missing block on the bottom right.

2023-10-25 04:15 UTC, HengchengZhang commented
> @HengchengZhang can you please let me know if you have time to fix these items this week?

Hi @mmcky I will fix the requests this week.

2023-10-25 04:15 UTC, mmcky commented
> > Thanks @HengchengZhang
> > I know there is a drive to simplify these pages -- but I think this page would look better with the card style objects (as we had on the more complex filtered page). So perhaps we can try static pages (with the card style objects)
> > <img alt="Screenshot 2023-10-25 at 2 42 27 pm" width="1332" src="https://user-images.githubusercontent.com/8263752/277866566-e2246538-c929-4d63-b186-129cf425209a.png">
> > the card style is
> > <img alt="Screenshot 2023-10-25 at 2 44 11 pm" width="1332" src="https://user-images.githubusercontent.com/8263752/277866850-73131858-dd2b-4606-9f47-5b46e0ca944d.png">
> > then we can make use of the filters on the `lectures` page to filter for `language` such as `julia` and `python`
> 
> Thanks @mmcky and main reason I'm making it simpler is that John thought that it's not very nice if we don't have 3's multiplier's number of cards. Cause currently if we go to the lectures filter there will be one missing block on the bottom right.

thanks @HengchengZhang can you match the style then of the cards in the linear list format?

2023-10-27 04:27 UTC, HengchengZhang commented on _layouts/home.html
> +    <div class="container">
I think that's manually set by `data-aos-delay="150"` and I've set them to the same.

2023-10-27 04:53 UTC, HengchengZhang commented on _layouts/home.html
>                <p><a href="/projects/#filter=code" class="btn-learn-more">View libraries</a></p>
-> `/packages/`

2023-10-27 05:03 UTC, HengchengZhang commented
Thanks @HumphreyYang for the review and I've updated all the changes. 

Hi @mmcky do I open a new branch to see how the horizontal cards style looks like with the language filter added? I actually tried horizontal cards style and its basically the current style without the filters label.

2023-10-30 00:55 UTC, mmcky commented
@HengchengZhang the best is to work locally and use screenshots so we can iterate more quickly.

2023-10-30 22:10 UTC, mmcky commented
@HengchengZhang I just spent some time this morning looking at the css styles

What do you think of this

<img width="1473" alt="Screenshot 2023-10-31 at 9 09 04 am" src="https://github.com/QuantEcon/website/assets/8263752/695c5762-be06-4eaf-9db9-7ab5d57fcf27">

@jstac we could use the label and filter infrastructure to organise by difficulty?

2023-10-31 00:54 UTC, mmcky commented
@HengchengZhang I have update the styles for `lectures` in [3e8ac43](https://github.com/QuantEcon/website/pull/113/commits/3e8ac4354683bc96aeecca59c946d7efee2959c8) and commented out the filters for now. We may use them to filter or sort for difficulty etc. later on. 

Can you let me know where `packages`, `books` and `others` are generated from?

2023-10-31 01:09 UTC, mmcky commented
> Can you let me know where packages, books and others are generated from?

OK I think I have figured this out -- they are in `pages/code` but it is confusing how they are different to `_lectures`. I think it would be great if we can standardise.

2023-10-31 01:55 UTC, mmcky commented
@HumphreyYang @HengchengZhang I have update the styles associated with the dropdown pages from `Projects` including `Lectures`, `Code`, `Books, and `Others`

If one of you could cast an eye over the build

https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app

and let me know what you think or spot any issues that would be great.

I would like to merge this tomorrow. 

cc: @jstac new build of website update.

2023-10-31 02:01 UTC, HumphreyYang commented
Many thanks @mmcky,

There are some very minor link issues. Would you mind if I push some changes to this branch now?

2023-10-31 02:03 UTC, mmcky commented
@HumphreyYang just reviewing myself

This is no longer fully relevant with the reorganised drop-down menu arrangement. 

<img width="1179" alt="Screenshot 2023-10-31 at 1 02 14 pm" src="https://github.com/QuantEcon/website/assets/8263752/c0a60cab-c9aa-47d2-8b79-c7c4ab0f374e">

We should:

- [ ] remove `all` as there is no all page
- [ ] Update to mirror the dropdown menu items

2023-10-31 02:04 UTC, HumphreyYang commented
> @HumphreyYang just reviewing myself
> 
> This is no longer fully relevant with the reorganised drop-down menu arrangement.
> 
> <img alt="Screenshot 2023-10-31 at 1 02 14 pm" width="1179" src="https://user-images.githubusercontent.com/8263752/279237286-c0a60cab-c9aa-47d2-8b79-c7c4ab0f374e.png">
> We should:
> 
> * [ ]  remove `all` as there is no all page
> * [ ]  Update to mirror the dropdown menu items

Many thanks @mmcky, this is exactly where I was.

2023-10-31 02:07 UTC, HumphreyYang commented
I think we can probably remove the projects section, as we already have this on the top of the page:

<img width="1499" alt="Screenshot 2023-10-31 at 13 06 35" src="https://github.com/QuantEcon/website/assets/39026988/8baf878a-1c20-46a0-919e-47b95f043080">

2023-10-31 02:07 UTC, mmcky commented
@HumphreyYang any thoughts on

> Should we update to mirror the dropdown menu items?

maybe I will leave it as this for now

<img width="1179" alt="Screenshot 2023-10-31 at 1 07 06 pm" src="https://github.com/QuantEcon/website/assets/8263752/2931076d-2b60-4786-ae79-7c03b9e0ec79">

2023-10-31 02:08 UTC, mmcky commented
@jstac here is the latest preview of new site

https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app

2023-10-31 02:09 UTC, HengchengZhang commented
> I think we can probably remove the projects section, as we already have this on the top of the page:
> 
> <img alt="Screenshot 2023-10-31 at 13 06 35" width="1499" src="https://user-images.githubusercontent.com/39026988/279237895-8baf878a-1c20-46a0-919e-47b95f043080.png">

I think Tom and John wants to have the lectures and books on homepage.

2023-10-31 02:11 UTC, HumphreyYang commented
> I think Tom and John wants to have the lectures and books on homepage.

Many thanks @HengchengZhang, I was referring to the projects section:

![image](https://github.com/QuantEcon/website/assets/39026988/debf2bed-cb23-4e0f-8835-51bc56aa7f1d)

They have some overlaps such as lectures and code.

2023-10-31 02:19 UTC, mmcky commented
I agree @HumphreyYang the `Lectures` and `Code` are duplicates and can be removed. Let's use this space to showcase `Notes` and `Executable Books` for now as Projects we work on.

2023-10-31 02:22 UTC, HumphreyYang commented
Many thanks @mmcky,

There is a link to lecture in [about](https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app/about/) page, which is yet updated.

2023-10-31 02:32 UTC, mmcky commented
Thanks @HumphreyYang 

I have now reviewed the `about` page and updated a bunch of links as suggested. I have also updated the content a little to better represent the new structure.

2023-10-31 02:33 UTC, HumphreyYang commented
Many thanks @mmcky,

Back to [2022]( https://web.archive.org/web/20220318063212/https://quantecon.org/), we have a title for the sponsors section. Do you think it is necessary to add it back as it is the only section without a title?

2023-10-31 02:37 UTC, HumphreyYang commented
> Thanks @HumphreyYang
> 
> I have now reviewed the `about` page and updated a bunch of links as suggested. I have also updated the content a little to better represent the new structure.

Many thanks @mmcky, I clicked all the links, and they are working well for me now.

2023-10-31 02:45 UTC, mmcky commented
> > Thanks @HumphreyYang
> > I have now reviewed the `about` page and updated a bunch of links as suggested. I have also updated the content a little to better represent the new structure.
> 
> Many thanks @mmcky, I clicked all the links, and they are working well for me now.

@HumphreyYang this is now in the footer

<img width="299" alt="Screenshot 2023-10-31 at 1 44 58 pm" src="https://github.com/QuantEcon/website/assets/8263752/61b3c73f-4e1c-4601-b56b-ec83bd907b46">

2023-10-31 02:48 UTC, mmcky commented
@HumphreyYang oh I think you mean this section

<img width="1420" alt="Screenshot 2023-10-31 at 1 47 29 pm" src="https://github.com/QuantEcon/website/assets/8263752/ec558f08-6e2a-4bc8-b051-838d46022340">

@jstac given we have these in the footer now -- do you think we can remove this panel to simplify the page?

2023-10-31 02:50 UTC, HumphreyYang commented
> > > Thanks @HumphreyYang
> > > I have now reviewed the `about` page and updated a bunch of links as suggested. I have also updated the content a little to better represent the new structure.
> > 
> > 
> > Many thanks @mmcky, I clicked all the links, and they are working well for me now.
> 
> @HumphreyYang this is now in the footer
> 
> <img alt="Screenshot 2023-10-31 at 1 44 58 pm" width="299" src="https://user-images.githubusercontent.com/8263752/279243533-61b3c73f-4e1c-4601-b56b-ec83bd907b46.png">

Apologize for the confusion @mmcky, I was referring to the section here:

<img width="1498" alt="Screenshot 2023-10-31 at 13 46 27" src="https://github.com/QuantEcon/website/assets/39026988/e9947b2c-a87a-485a-b722-b28d8fb56dc7">

Also, What is your opinion on renaming this section

<img width="1243" alt="Screenshot 2023-10-31 at 13 48 25" src="https://github.com/QuantEcon/website/assets/39026988/c126d216-5b80-4cfc-91f8-c1b17370c007">

as "Other Projects" and add  

<img width="1448" alt="Screenshot 2023-10-31 at 13 49 05" src="https://github.com/QuantEcon/website/assets/39026988/c1df3fa1-ca1c-4bcd-bf5f-860dcd20e5a2">

into this block?

2023-10-31 02:54 UTC, mmcky commented
Thanks for these thoughts @HumphreyYang 

> as "Other Projects" and add some of the other items on this page

I actually think it would be great to showcase our Open Source contributions (Infrastructure projects). The Other Projects are available through the menubar. The main one would be to promote our `Workshops` on the front page somewhere.

2023-10-31 02:56 UTC, mmcky commented
@HumphreyYang our workshops is front and centre in this panel

<img width="1420" alt="Screenshot 2023-10-31 at 1 55 52 pm" src="https://github.com/QuantEcon/website/assets/8263752/ac4c49e4-1f36-4d11-a420-e2e7dab70581">

but we should add a `Past Workshops` link to this panel.

2023-10-31 03:00 UTC, HumphreyYang commented
> Thanks for these thoughts @HumphreyYang
> 
> > as "Other Projects" and add some of the other items on this page
> 
> I actually think it would be great to showcase our Open Source contributions (Infrastructure projects). The Other Projects are available through the menubar. The main one we should promote to the front page is `Workshops` though.

Many thanks @mmcky, this also sounds great to me. I think the only concern I have is the title "Open Source" is a little bit too general as our lectures, code, and books are also open-sourced. Perhaps we can say "Open Source Contributions" / "Open Source Infrastructures". Sorry, I couldn't think of a better title for this but I think you will have a much better idea of the title here.

2023-10-31 03:02 UTC, HumphreyYang commented
> @HumphreyYang our workshops is front and centre in this panel
> 
> <img alt="Screenshot 2023-10-31 at 1 55 52 pm" width="1420" src="https://user-images.githubusercontent.com/8263752/279245272-ac4c49e4-1f36-4d11-a420-e2e7dab70581.png">
> but we should add a `Past Workshops` link to this panel.

It's a great idea. I think we can put a link at "Post locations" or "remote and in-person workshops and short courses" without having another button here.

2023-10-31 03:05 UTC, mmcky commented
> @HumphreyYang our workshops is front and centre in this panel
> 
> <img alt="Screenshot 2023-10-31 at 1 55 52 pm" width="1420" src="https://user-images.githubusercontent.com/8263752/279245272-ac4c49e4-1f36-4d11-a420-e2e7dab70581.png">
> but we should add a `Past Workshops` link to this panel.

@HumphreyYang I was thinking the same. Link has now been added for `Past locations` text

<img width="1420" alt="Screenshot 2023-10-31 at 2 04 20 pm" src="https://github.com/QuantEcon/website/assets/8263752/e6ac60dc-f8b8-4189-bdbc-4774b964ac74">

BTW -- something weird jut happened and I may have edited one of your recent blocks?

2023-10-31 03:06 UTC, mmcky commented
> > Thanks for these thoughts @HumphreyYang
> > > as "Other Projects" and add some of the other items on this page
> > 
> > 
> > I actually think it would be great to showcase our Open Source contributions (Infrastructure projects). The Other Projects are available through the menubar. The main one we should promote to the front page is `Workshops` though.
> 
> Many thanks @mmcky, this also sounds great to me. I think the only concern I have is the title "Open Source" is a little bit too general as our lectures, code, and books are also open-sourced. Perhaps we can say "Open Source Contributions" / "Open Source Infrastructures". Sorry, I couldn't think of a better title for this but I think you will have a much better idea of the title here.

No worries. Thanks for these thoughts. I'll keep it simple and `least words` for now and we can improve later if we need to.

2023-10-31 03:08 UTC, HumphreyYang commented
> BTW -- something weird jut happened and I may have edited one of your recent blocks?

I think one of my comments is deleted : ) nothing too dramatic.

2023-10-31 03:08 UTC, HumphreyYang approved these changes

2023-10-31 03:10 UTC, mmcky commented
thanks for review @HumphreyYang 

@jstac this is now ready for review. 

Only outstanding item is:

- [ ] should we remove the large sponsor panel in favour of just listing them in the `Sponsor` area in the footer.

2023-10-31 03:16 UTC, HumphreyYang commented
Sorry for the late message @mmcky, there are two more links to be checked on the [about](https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app/about/) page:

One is the link to the team page:
<img width="1085" alt="Screenshot 2023-10-31 at 14 13 43" src="https://github.com/QuantEcon/website/assets/39026988/84c40671-04e3-4082-bcd8-8e8299fa12d9">

The other is to the direct donation:
<img width="558" alt="Screenshot 2023-10-31 at 14 13 47" src="https://github.com/QuantEcon/website/assets/39026988/6a66eb8a-b833-40ea-8c4c-5fdf4f108afb">

It indicates that the donation project has ended.

2023-10-31 03:19 UTC, mmcky commented
thanks @HumphreyYang both of those links are now fixed and updated

2023-10-31 04:06 UTC, jstac commented
Great work guys.  Just the issue of the images being too small here: https://deploy-preview-113--sleepy-aryabhata-461b8b.netlify.app/books/

> should we remove the large sponsor panel in favour of just listing them in the Sponsor area in the footer.

I think it's good as is.  We will probably have to add the Chow Institute soon.

2023-10-31 06:06 UTC, mmcky commented
thanks @jstac

2023-10-31 06:09 UTC, merged